# 23-02-2026

In [2]:
import pandas as pd
import numpy as np

In [3]:
myList = [1,2,3,4]

array = np.random.randint(10,20,4)

In [4]:
print(array)
myList

[19 11 11 11]

[1, 2, 3, 4]

In [5]:
s1 = pd.Series(myList)
s1
# Series - 1D collection of data with index
# Non homogeneous data - can contain different types of data
# Indexes can be custom defined

0    1
1    2
2    3
3    4
dtype: int64

In [6]:
s2 = pd.Series(array)
s2

0    19
1    11
2    11
3    11
dtype: int32

In [7]:
mylist = [5,4,6,1,1.7,99.8]
myarray = np.array(mylist)

In [10]:
myseries1 = pd.Series(data=mylist)
print(myseries1)
myseries2 = pd.Series(data=myarray)
print(myseries2)

df = pd.concat([myseries1,myseries2],axis=1)
print(df)
df = pd.concat([myseries1,myseries2],axis=0) # DataFrame - 2D collection of data with index and columns
print(df)

0     5.0
1     4.0
2     6.0
3     1.0
4     1.7
5    99.8
dtype: float64
0     5.0
1     4.0
2     6.0
3     1.0
4     1.7
5    99.8
dtype: float64
      0     1
0   5.0   5.0
1   4.0   4.0
2   6.0   6.0
3   1.0   1.0
4   1.7   1.7
5  99.8  99.8
0     5.0
1     4.0
2     6.0
3     1.0
4     1.7
5    99.8
0     5.0
1     4.0
2     6.0
3     1.0
4     1.7
5    99.8
dtype: float64

In [14]:
mylables = ['first', 'second', 'third', 'fourth']
# myseries3 = pd.Series(data=mylist, index=mylables)
# print(myseries3)
myseries4 = pd.Series(data=myarray, index=mylist)
print(myseries4)

5.0      5.0
4.0      4.0
6.0      6.0
1.0      1.0
1.7      1.7
99.8    99.8
dtype: float64

# 25-02-2026

In [3]:
# Series from Dictonary
s3 = pd.Series({'apple':7, 'mango':18, 'banana':45})
s3

apple      7
mango     18
banana    45
dtype: int64

In [6]:
print("Values: ", s3.values)
print("Indexes: ", s3.index)

Values:  [ 7 18 45]
Indexes:  Index(['apple', 'mango', 'banana'], dtype='str')

In [4]:
df1 = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [10, 20, 30]
})
print(df1)

   A   B
0  1  10
1  2  20
2  3  30

In [ ]:
# Basic Attributes of DataFrame
print("Shape: ", df1.shape)
print("Coloumns: ", df1.columns)
print("Index: ", df1.index)
print("Data Types: ", df1.dtypes)

Shape:  (3, 2)
Coloumns:  Index(['A', 'B'], dtype='str')
Index:  RangeIndex(start=0, stop=3, step=1)
Data Types:  A    int64
B    int64
dtype: object

In [ ]:
df1.head() # Default 5 rows

   A   B
0  1  10
1  2  20
2  3  30

In [ ]:
df1.tail() # Default last 5 rows

   A   B
0  1  10
1  2  20
2  3  30

In [16]:
df1.head(1)

   A   B
0  1  10

In [17]:
df1.tail(1)

   A   B
2  3  30

In [ ]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes

In [20]:
# Statistical Summary
df1.describe()

         A     B
count  3.0   3.0
mean   2.0  20.0
std    1.0  10.0
min    1.0  10.0
25%    1.5  15.0
50%    2.0  20.0
75%    2.5  25.0
max    3.0  30.0

In [22]:
df1.describe().T

   count  mean   std   min   25%   50%   75%   max
A    3.0   2.0   1.0   1.0   1.5   2.0   2.5   3.0
B    3.0  20.0  10.0  10.0  15.0  20.0  25.0  30.0

In [23]:
df2 = pd.DataFrame({"Name": ["John", "Jane", "Doe"], "Age": [25, 30, 35], 'Salary': [50000, 60000, 70000]})
print(df2)

   Name  Age  Salary
0  John   25   50000
1  Jane   30   60000
2   Doe   35   70000

In [31]:
print("Summary: ", df2.info())
print("\nStatistical Summary:\n", df2.describe().T)

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Salary  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes
Summary:  None

Statistical Summary:
         count     mean      std      min      25%      50%      75%      max
Age       3.0     30.0      5.0     25.0     27.5     30.0     32.5     35.0
Salary    3.0  60000.0  10000.0  50000.0  55000.0  60000.0  65000.0  70000.0

In [33]:
# Full satistics summary of the data
df2.describe(include='all')

        Name   Age   Salary
count      3   3.0      3.0
unique     3   NaN      NaN
top     John   NaN      NaN
freq       1   NaN      NaN
mean     NaN  30.0  60000.0
std      NaN   5.0  10000.0
min      NaN  25.0  50000.0
25%      NaN  27.5  55000.0
50%      NaN  30.0  60000.0
75%      NaN  32.5  65000.0
max      NaN  35.0  70000.0

In [6]:
# Alphanumeric dataframe example
df3 = pd.DataFrame({
    "Name": ["John", "Jane", "Doe", "Smith", "Emily", "Roman"],
    "Age": [25, 30, 35, 40, 45, 50],
    "City": ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'New York'],
    'Salary': [50000, 60000, 70000, 80000, 90000, 100000],
    'Department': ['HR', 'Finance', 'IT', 'Marketing', 'HR', 'IT']
})

In [7]:
# Statistical Summary
df3.describe(include='all') # Include all data types in the summary

        Name        Age      City         Salary Department
count      6   6.000000         6       6.000000          6
unique     6        NaN         5            NaN          4
top     John        NaN  New York            NaN         HR
freq       1        NaN         2            NaN          2
mean     NaN  37.500000       NaN   75000.000000        NaN
std      NaN   9.354143       NaN   18708.286934        NaN
min      NaN  25.000000       NaN   50000.000000        NaN
25%      NaN  31.250000       NaN   62500.000000        NaN
50%      NaN  37.500000       NaN   75000.000000        NaN
75%      NaN  43.750000       NaN   87500.000000        NaN
max      NaN  50.000000       NaN  100000.000000        NaN

In [8]:
df3

    Name  Age         City  Salary Department
0   John   25     New York   50000         HR
1   Jane   30  Los Angeles   60000    Finance
2    Doe   35      Chicago   70000         IT
3  Smith   40      Houston   80000  Marketing
4  Emily   45      Phoenix   90000         HR
5  Roman   50     New York  100000         IT

In [9]:
df3["Salary"].unique()

array([ 50000,  60000,  70000,  80000,  90000, 100000])

In [10]:
df3.Department.value_counts()

Department
HR           2
IT           2
Finance      1
Marketing    1
Name: count, dtype: int64

# 27-02-2026

In [11]:
print("Single Coloumn (Series):\n", df3["Name"])
print("\nMultiple Coloumns (DataFrame):\n", df3[["Name", "Salary"]])

Single Coloumn (Series):
 0     John
1     Jane
2      Doe
3    Smith
4    Emily
5    Roman
Name: Name, dtype: str

Multiple Coloumns (DataFrame):
     Name  Salary
0   John   50000
1   Jane   60000
2    Doe   70000
3  Smith   80000
4  Emily   90000
5  Roman  100000

In [12]:
df3.loc[0] # Accessing first row using loc

Name              John
Age                 25
City          New York
Salary           50000
Department          HR
Name: 0, dtype: object

In [13]:
df3.iloc[0] # Accessing first row using iloc

Name              John
Age                 25
City          New York
Salary           50000
Department          HR
Name: 0, dtype: object

In [14]:
import pandas as pd
import numpy as np

In [15]:
df4 = pd.DataFrame(np.arange(1,26).reshape(5, 5), index=['first row', 'second row', 'third row', 'fourth row', 'fifth row'],
                   columns=['first coloumn', 'second coloumn', 'third coloumn', 'fourth coloumn', 'fifth coloumn'])
df4

,first coloumn,second coloumn,third coloumn,fourth coloumn,fifth coloumn
first row,1,2,3,4,5
second row,6,7,8,9,10
third row,11,12,13,14,15
fourth row,16,17,18,19,20
fifth row,21,22,23,24,25

In [16]:
df4.loc["first row", "first coloumn"] # Accessing specific cell using loc

np.int64(1)

In [17]:
# df4.loc(1, 2)

In [18]:
df4.iloc[1, 2]

np.int64(8)

In [19]:
df4.iloc[1:,:2]

            first coloumn  second coloumn
second row              6               7
third row              11              12
fourth row             16              17
fifth row              21              22

In [20]:
df4.iloc[1:2,3::-1]

            fourth coloumn  third coloumn  second coloumn  first coloumn
second row               9              8               7              6

In [21]:
df4.iloc[4::-2,2::-2]

           third coloumn  first coloumn
fifth row             23             21
third row             13             11
first row              3              1

In [22]:
df4.iloc[::-2,5::-2] # Extra range can be given, it will not throw error but will return the available data in the range.

           fifth coloumn  third coloumn  first coloumn
fifth row             25             23             21
third row             15             13             11
first row              5              3              1

## Reading Files

In [23]:
import pandas as pd
import numpy as np

In [24]:
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [25]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [26]:
survived = df[df["Survived"] == 1 & (df["Age"] < 20)]
survived

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# 06-0-2026

### Boolean Indexing

In [27]:
df3

    Name  Age         City  Salary Department
0   John   25     New York   50000         HR
1   Jane   30  Los Angeles   60000    Finance
2    Doe   35      Chicago   70000         IT
3  Smith   40      Houston   80000  Marketing
4  Emily   45      Phoenix   90000         HR
5  Roman   50     New York  100000         IT

In [28]:
high_salary = df3[df3["Salary"] > 50000]
print("Employees with high salary:\n", high_salary)

Employees with high salary:
     Name  Age         City  Salary Department
1   Jane   30  Los Angeles   60000    Finance
2    Doe   35      Chicago   70000         IT
3  Smith   40      Houston   80000  Marketing
4  Emily   45      Phoenix   90000         HR
5  Roman   50     New York  100000         IT

In [29]:
salary = df3[((df3["Salary"] == 50000) | (df3["City"] == 'New York'))]
print("Employees with salary 50000 or from New York:\n", salary)

Employees with salary 50000 or from New York:
     Name  Age      City  Salary Department
0   John   25  New York   50000         HR
5  Roman   50  New York  100000         IT

In [30]:
salary = df3[((df3["Salary"] == 50000) & (df3["City"] == 'New York'))]
salary

   Name  Age      City  Salary Department
0  John   25  New York   50000         HR

In [31]:
salary1 = df3[(df3["Age"] != 25) & (df3["Salary"] != 70000)]
salary1

    Name  Age         City  Salary Department
1   Jane   30  Los Angeles   60000    Finance
3  Smith   40      Houston   80000  Marketing
4  Emily   45      Phoenix   90000         HR
5  Roman   50     New York  100000         IT

In [32]:
df3_renamed = df3.rename(columns={"Name": "Employee", "Salary": "Income"})
df3_renamed

  Employee  Age         City  Income Department
0     John   25     New York   50000         HR
1     Jane   30  Los Angeles   60000    Finance
2      Doe   35      Chicago   70000         IT
3    Smith   40      Houston   80000  Marketing
4    Emily   45      Phoenix   90000         HR
5    Roman   50     New York  100000         IT